In [1]:
from array import *

In [2]:
arr1 = array('i', [1,2,3,4,5,6])

In [3]:
print(arr1)

array('i', [1, 2, 3, 4, 5, 6])


### Insert into an array

In [4]:
arr1.insert(6,7)

In [5]:
print(arr1)

array('i', [1, 2, 3, 4, 5, 6, 7])


### Traversing an Array

In [6]:
def traverseArray(array):
    for i in array:
        print(i)

In [7]:
traverseArray(arr1)

1
2
3
4
5
6
7


### Accessing an Array

In [8]:
def accessArray(array, index):
    if index >= len(array):
        print('Error')
    else:
        print(array[index])
        

In [9]:
accessArray(arr1, 5)

6


In [10]:
arr1[5]

6

### Linear Search Algorithm to Find an Array

In [11]:
def linearsearch(array, target):
    for i in range(len(array)):
        if array[i] == target:
            return i
    return -1

In [27]:
print(linearsearch(arr1, 3))

2


### Removing an elemnt formt he array

In [13]:
arr1.remove(5)

print(arr1)

array('i', [1, 2, 3, 4, 6, 7])


### 2D Array

In [14]:
import numpy as np

In [15]:
twoDArray = np.array([[11,15,10,6], [10,14,11,5], [12,17,12,8], [15,18,14,9]])

print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


### Inserting a value in 2D Array

In [16]:
newtwoDArray = np.insert(twoDArray, 0, [[1,2,3,4]], axis=0) # Axis=1 will add to the column
# np.append(twoDArray, [[1,2,3,4], axis=0]) this can be done if array row or column needs to
# be added at the end of the matrix 2D Array.

print(newtwoDArray)

[[ 1  2  3  4]
 [11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


### Accessing an element in 2D Array

In [17]:
def accessElements(array, rowIndex, columnIndex):
    if rowIndex >= len(array) or columnIndex >= len(array[0]):
        print('Incorrect Index')
    else:
        print(array[rowIndex][columnIndex])

In [18]:
accessElements(newtwoDArray, 2,2)

11


### Traversing through a 2D Array

In [19]:
def traversetwoDArray(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])
            

In [20]:
traversetwoDArray(newtwoDArray)

1
2
3
4
11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


### Searching through a 2D Array Linear Search Algo

In [21]:
def linearsearchTD(array, target):
    for i in range(len(array)):
        for j in range(len(array[0])):
            if array[i][j] == target:
                return 'The value is located at index ' +str(i)+" "+str(j)
    return -1

In [22]:
print(linearsearchTD(newtwoDArray, 12))

The value is located at index 3 0


In [23]:
def linearsearchTDD(array, target):
    result = []  # List to store all the indices where the target is found
    for i in range(len(array)):           # Loop through the rows
        for j in range(len(array[0])):    # Loop through the columns
            if array[i][j] == target:     # Check if the current element matches the target
                result.append((i, j))     # Add the index (i, j) to the result list
    if result:                            # If the result list is not empty (i.e., target was found)
        return f'The value is located at indices: {result}'
    else:
        return -1  # If the target was not found in the array


In [24]:
linearsearchTDD(newtwoDArray, 12)

'The value is located at indices: [(3, 0), (3, 2)]'

### Deleting in 2D Array

In [25]:
deleteArray = np.delete(newtwoDArray, 0, axis = 0)

In [26]:
print(deleteArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
